#!/usr/bin/env bash
# Setting up server to curl port 80 with no issues
apt-get update
apt-get -y install curl
rm /etc/nginx/sites-available/*
rm /etc/nginx/sites-enabled/*~
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
sudo service nginx restart
